### ISSUE TITLE
Code improvements based on Hafiz's decentralized PCA

### ISSUE THREAD

**Issue by hvgazula** [trendscenter/coinstac_globalpca#5]
More here https://github.com/MRN-Code/decentralized-pca

I couldn't add @rsilva and @hafizimtiaz here. Probably, because it's a private repo.

**Comment by bbradt** [comment]
@hvgazula 

Can you outline specifically what the improvements are?

**Comment by hvgazula** [comment]
@bbradt  the same things we spoke of..min/max of ranks..checking for complex numbers etc etc
